#zk:
#  address: 114.55.88.188:2181,114.55.88.188:2182,114.55.88.188:2183

#服务名
dubbo:
  application:
    name: kohService
  #注册的组
  registry:
    protocol: zookeeper
    #zookeeper地址
    address: 34.214.167.47:2181,34.218.222.177:2181,54.202.149.169:2181
  annotation:
    package: com.koh
  provider:
    delay: -1
    timeout: 5000
    retries: 0
    threads: 300
    dispatcher: message
    cluster: failover
    filter: -validation
  protocol:
    name: dubbo

thrift:
  server:
    configs:
       - name: testService
         port: 30880
         threads: 100
       - name: secondService
         port: 30881
         threads: 100
  client:
    timeout: 3000
    pool:
      maxTotal: 30
      maxIdle: 30
      minIdle: 0
      maxWait: 5000



